import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { TemplateDefinition } from '../models';

@Injectable({
  providedIn: 'root'
})
export class TemplatesService {
  private mockTemplates: TemplateDefinition[] = [
    {
      id: 'PMO-TPL-001',
      name: 'Project Intake',
      version: '2.0',
      lastUpdated: '2026-04-15',
      gate: 'Gate 1',
      tierApplicability: 'T1, T2, T3',
      description: 'Initial project intake form for governance tier assessment and intake approval.',
      templateUrl: 'https://sharepoint.venturacounty.gov/teams/pmo/Shared%20Documents/PMO-TPL-001.pdf',
      instructionsUrl:
          'https://sharepoint.venturacounty.gov/teams/pmo/Shared%20Documents/PMO-TPL-001-Instructions.pdf',
      submitEnabled: true,
      availableActions: ['DETAILS', 'DOWNLOAD', 'INSTRUCTIONS', 'SUBMIT']
    },
    {
      id: 'PMO-TPL-002',
      name: 'Project Charter',
      version: '1.5',
      lastUpdated: '2026-04-10',
      gate: 'Gate 2',
      tierApplicability: 'T1, T2',
      description: 'Project charter and governance confirmation at Gate 2 approval.',
      templateUrl: 'https://sharepoint.venturacounty.gov/teams/pmo/Shared%20Documents/PMO-TPL-002.pdf',
      instructionsUrl:
          'https://sharepoint.venturacounty.gov/teams/pmo/Shared%20Documents/PMO-TPL-002-Instructions.pdf',
      submitEnabled: true,
      availableActions: ['DETAILS', 'DOWNLOAD', 'INSTRUCTIONS', 'SUBMIT']
    },
    {
      id: 'PMO-TPL-003',
      name: 'Release Readiness',
      version: '1.0',
      lastUpdated: '2026-04-01',
      gate: 'Gate 4',
      tierApplicability: 'T1, T2, T3',
      description: 'Release readiness assessment and cutover planning validation.',
      templateUrl: 'https://sharepoint.venturacounty.gov/teams/pmo/Shared%20Documents/PMO-TPL-003.pdf',
      instructionsUrl:
          'https://sharepoint.venturacounty.gov/teams/pmo/Shared%20Documents/PMO-TPL-003-Instructions.pdf',
      submitEnabled: false,
      availableActions: ['DETAILS', 'DOWNLOAD', 'INSTRUCTIONS', 'UPLOAD_DOCUMENT']
    },
    {
      id: 'PMO-TPL-004',
      name: 'Project Closure',
      version: '1.2',
      lastUpdated: '2026-03-20',
      gate: 'Gate 5',
      tierApplicability: 'T1, T2, T3',
      description: 'Project closure report, lessons learned, and benefits realization.',
      templateUrl: 'https://sharepoint.venturacounty.gov/teams/pmo/Shared%20Documents/PMO-TPL-004.pdf',
      instructionsUrl:
          'https://sharepoint.venturacounty.gov/teams/pmo/Shared%20Documents/PMO-TPL-004-Instructions.pdf',
      submitEnabled: true,
      availableActions: ['DETAILS', 'DOWNLOAD', 'INSTRUCTIONS', 'SUBMIT']
    },
    {
      id: 'PMO-TPL-005',
      name: 'RAID Log',
      version: '2.1',
      lastUpdated: '2026-04-18',
      tierApplicability: 'T1, T2',
      description: 'Risks, Assumptions, Issues, and Dependencies tracking log.',
      templateUrl: 'https://sharepoint.venturacounty.gov/teams/pmo/Shared%20Documents/PMO-TPL-005.xlsx',
      instructionsUrl:
          'https://sharepoint.venturacounty.gov/teams/pmo/Shared%20Documents/PMO-TPL-005-Instructions.pdf',
      submitEnabled: false,
      availableActions: ['DETAILS', 'DOWNLOAD', 'INSTRUCTIONS', 'UPLOAD_DOCUMENT']
    },
    {
      id: 'PMO-TPL-006',
      name: 'Gate Decision Record',
      version: '1.3',
      lastUpdated: '2026-04-05',
      tierApplicability: 'T1, T2, T3',
      description: 'Gate decision record and approval documentation (generated by PMO).',
      templateUrl: 'https://sharepoint.venturacounty.gov/teams/pmo/Shared%20Documents/PMO-TPL-006.pdf',
      instructionsUrl:
          'https://sharepoint.venturacounty.gov/teams/pmo/Shared%20Documents/PMO-TPL-006-Instructions.pdf',
      submitEnabled: false,
      generatedByPmo: true,
      availableActions: ['DETAILS', 'DOWNLOAD', 'INSTRUCTIONS', 'VIEW_RECORDS']
    }
  ];

  /**
   * Get all templates
   */
  getTemplates(): Observable<TemplateDefinition[]> {
    // TODO(api): Replace with HttpClient GET /api/templates
    return of(this.mockTemplates);
  }

  /**
   * Get template by ID
   */
  getTemplate(templateId: string): Observable<TemplateDefinition | undefined> {
    const template = this.mockTemplates.find((t) => t.id === templateId);
    return of(template);
  }

  /**
   * API-aligned alias for template lookup
   */
  getTemplateById(templateId: string): Observable<TemplateDefinition | undefined> {
    // TODO(api): Replace with HttpClient GET /api/templates/{templateId}
    return this.getTemplate(templateId);
  }

  /**
   * Get submittable templates (Intake, Charter, Closure)
   */
  getSubmittableTemplates(): Observable<TemplateDefinition[]> {
    const submittable = this.mockTemplates.filter(
        (t) =>
            t.id === 'PMO-TPL-001' ||
            t.id === 'PMO-TPL-002' ||
            t.id === 'PMO-TPL-004'
    );
    return of(submittable);
  }

  /**
   * Get templates that require upload/document handling
   */
  getUploadTemplates(): Observable<TemplateDefinition[]> {
    return of(this.mockTemplates.filter((template) => template.availableActions?.includes('UPLOAD_DOCUMENT')));
  }
}
